<%@ Page Language="C#" MasterPageFile="~/Default.Master" AutoEventWireup="true" CodeBehind="SYSMenuCtl.aspx.cs" Inherits="WaveLab.Web.SYSMenuCtl" Title="无标题页"  meta:resourcekey="PageResource"  %>
<asp:Content ID="ctHead" ContentPlaceHolderID="headPlaceHolder" runat="server">
<script type ="text/javascript">
$(document).ready( function() {
	$("input:submit").button();
});
function makeWindow(mode,value)
{
    var url;
    switch(mode)
    {
        case "NEW":
            url = "SYSMenuNew.aspx";
            break;
        case "EDIT":
            url = "SYSMenuEdit.aspx?menuid=" + value;
            break ;
        case "AC":
            url = "SYSMenuAC.aspx?menuid=" + value;
            break;
        case "OR":
            url = "SYSMenuOrder.aspx?parentid=" + value;
            break;
        default:
            break;
     
    }
    var winparas="toolbar=0,status=0,scrollbars=1,resizable=0,width=700px,Height=500px";
    var win=window.open(url,"secwin",winparas);
    return false;
}
</script>
</asp:Content>
<asp:Content ID="ctMain" ContentPlaceHolderID="bodyPlaceHolder" runat="server">
<table >
	<tr>
		<td><asp:Image ID ="imgTitle" runat="server" SkinID ="ImgskinTitle" 
			meta:resourcekey="imgTitleResource1" /></td>
		<td valign="bottom"><asp:Label ID ="lblTitle" runat="server"  SkinID ="skinTitle" 
			meta:resourcekey="lblTitleResource1" /></td>
	</tr>
</table>
<center>
    <table width ="800" style="text-align:left" border ="0" cellpadding="0" cellspacing ="0">
        <tr>
            <td align ="right" id="tdNew" runat="server"  colspan ="2">
             <asp:NewButton ID="btnNew" runat="server"  Width ="60px" Text ="<%$ Resources:globalResource,NewText %>"
                   Action ="MenuNew" OnClientClick ="return makeWindow('NEW','')"  /><br/>
            </td>
        </tr>
        <tr>
            <td  colspan ="2">
               <table width="100%"   style="font-weight:normal;" border ="0" cellpadding="0" cellspacing ="0">
                  <tr>
                    <td colspan="4">
                       <table width="100%"  >
                           <tr>
                              <th><asp:Label ID="lblMenuDesc" 
                                      runat="server" meta:resourcekey="lblMenuDescResource" /></th>
                              <th style="width:90px;word-wrap:break-word;">
                                  <asp:Label ID="lblAC" runat="server" meta:resourcekey="lblACResource" /></th>
                              <th style="width:80px;">
                                  <asp:Label ID="lblOrder" runat="server" meta:resourcekey="lblOrderResource" /></th>
                           </tr>
                       </table>
                    </td>
                  </tr>
                  <tr>
                      <td colspan ="4" >
                           <asp:UpdatePanel ID="upltreeView" runat="server">
                               <ContentTemplate>
                                    <asp:TreeView ID="tvMenu" runat="server" Width="100%"  AutoPostBack="true"  EnableViewState ="false" 
                                     CollapseImageToolTip="" ExpandImageToolTip="" NodeWrap="True" 
                                     AutoGenerateDataBindings="False" ShowLines="True"  ExpandDepth="0" 
                                          meta:resourcekey="FuntionTVResource1" 
                                          ontreenodecollapsed="tvMenu_TreeNodeCollapsed" 
                                          ontreenodeexpanded="tvMenu_TreeNodeExpanded">
                                           <NodeStyle  ForeColor="DarkBlue" Font-Underline="False" Width="100%" BorderStyle="None"  />
                                           <SelectedNodeStyle ForeColor="OrangeRed" />
                                    </asp:TreeView>
                               </ContentTemplate>
                               <Triggers>
                                    <asp:AsyncPostBackTrigger ControlID="tvMenu" EventName="TreeNodeExpanded" />
                                    <asp:AsyncPostBackTrigger ControlID="tvMenu" EventName="TreeNodeCollapsed" />
                                </Triggers>
                            </asp:UpdatePanel>
                      </td>
                  </tr>
               </table>
            </td>
        </tr>
 
    </table>
</center>
</asp:Content>
