<%@ Page Language="C#" MasterPageFile="~/Default.Master" AutoEventWireup="true" CodeBehind="SYSRoleActionAC.aspx.cs" Inherits="WaveLab.Web.SYSRoleActionAC" Title="无标题页" culture="auto" meta:resourcekey="PageResource1" uiculture="auto" %>
<asp:Content ID="Content1" ContentPlaceHolderID="headPlaceHolder" runat="server">
<script  type="text/javascript">
$(document).ready( function() {
	$("input:submit").button();
});
function redirect(mode,value)
{
    var url;
    switch (mode)
    {
        case "COPY":
            url = "SYSRoleActionACCopy.aspx?roleid=" + value;
            break;
        default:
            break;
    }
    self.location.href=url;
    return false;
}

function allCheck()
{
    $.each($("#<%=GVList.ClientID %> :checkbox:gt(0)"),function(){
            $(this).attr("checked", $("#allCheckBox").attr("checked"));
	    });
}
</script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="bodyPlaceHolder" runat="server">
 <center>
   <table style=" text-align:left ;" >
   <tr>
    <td>
        <table  cellpadding="5" cellspacing="0" style="text-align:left;" width="630px">
          <tr>
            <td>
                <asp:Label ID ="lblRole" runat="server" meta:resourcekey="lblRoleResource1" />&nbsp;&nbsp;
                <asp:Label ID="lblRoldeDesc" runat="server" ForeColor="Blue" 
                    meta:resourcekey="lblRoleDescResource1"/>
            </td>
             
         </tr>
         <tr>
             <td>
                <table width="100%">
                   <tr>
                       <td  valign="top" style ="width:205px">
                           <asp:Label ID="lblTVMenuTitle" runat="server" 
                                 meta:resourcekey="lblTVMenuTitleResource1" />
                       </td>
                       <td>
                          <asp:Label ID="lblActionTitle" runat="server" 
                                 meta:resourcekey="lblActionTitleResource1" />
                       </td>
                        <td align="right">
                             <asp:NewButton ID="btnCopy" runat="server" Width="60px" Action ="RoleActionMappingCopy"
                                 meta:resourcekey="btnCopyResource1" />
                             <asp:NewButton ID="btnCancel" runat="server" Width="60px" Text ="<%$ Resources:globalResource,CancelText %>"
                              OnClientClick ="return cancel()"/>
                        </td>
                  </tr>
                   <tr>
                      <td>
                           <div style="overflow :auto; height:400px; width:200px; border:solid 1px gray">
                                <asp:TreeView ID="tvACMenu" runat="server" Width="100%"  AutoPostBack="true"  
                                    CollapseImageToolTip="" ExpandImageToolTip="" NodeWrap="True" 
                                    AutoGenerateDataBindings="False" ShowLines="True"  ExpandDepth="0"  
                                    meta:resourcekey="tvACMenuResource1" 
                                    onselectednodechanged="tvACMenu_SelectedNodeChanged">
                                    <NodeStyle  ForeColor="DarkBlue" Font-Underline="False" Width="100%" BorderStyle="None"  />
                                    <SelectedNodeStyle ForeColor="#FF3300" BackColor="#FFCCFF" Font-Bold="True" 
                                        Font-Underline="True" />
                                </asp:TreeView>
                           </div>
                      </td>
                      <td valign ="top" colspan ="2">
                        <div style="overflow :auto; height:400px; width:450px; border:solid 1px gray">
                           <table id="actionTable" runat ="server" style = "width :100%">
                            <tr>
                                <td><asp:Label ID ="lblRecCount" runat ="server"  meta:resourcekey="lblRecCountResource1" /></td>
                            </tr>
                            <tr>
                                <td>
                                    <asp:GridView ID="GVList" runat="server" AllowSorting ="True"  SkinId="skinGridView"
                                AutoGenerateColumns="False"  Width ="100%" DataKeyNames ="ActionId"
                                meta:resourcekey="GVListResource1" onsorting="GVList_Sorting" 
                                         onrowdatabound="GVList_RowDataBound"  >
                                          <Columns>
                                             <asp:BoundField DataField ="Action" SortExpression ="action" 
                                                  meta:resourcekey="BoundFieldResource1" />
                                             <asp:BoundField DataField ="ActionName" SortExpression ="action_name" 
                                                  meta:resourcekey="BoundFieldResource2" />
                                             <asp:TemplateField meta:resourcekey="TemplateFieldResource1" >
                                                <HeaderTemplate >
                                                    <input type ="checkbox" id="allCheckBox" OnClick='JavaScript:allCheck()' />
                                                    <asp:Label ID="lblAll" runat="server" meta:resourcekey="lblAllResource1" />
                                                </HeaderTemplate>
                                                <ItemTemplate >
                                                    <asp:CheckBox ID="check" runat="server" meta:resourcekey="checkResource1" />
                                                </ItemTemplate>
                                             </asp:TemplateField>
                                          </Columns>
                                    </asp:GridView>
                                </td>
                            </tr>
                           </table>
                          </div>
                      </td>
                   </tr>
                   <tr>
                      <td></td>
                      <td  colspan ="2" align ="right">
                           <asp:NewButton ID="btnSave" runat ="server" Width="80px"  Text ="<%$ Resources:globalResource,SaveText %>"
                              Action ="RoleActionMappingSave" onclick="btnSave_Click" />
                          <asp:NewButton ID="btnReset" runat="server" Width="80px" Text ="<%$ Resources:globalResource,ResetText %>"
                              OnClientClick ="return refresh()"/>
                      </td>
                   </tr>
                </table>
             </td>
         </tr>
        </table>
     </td>
     </tr>
     </table>
</center>
</asp:Content>
